version: "3.9"
services:
  python-backend:
    container_name: python-backend
    build:
      context: ./app
      dockerfile: Dockerfile
    environment:
      - LOOKED_AWAY_THRESHOLD=7.5
      - HAPPY_TO_ANGRY_DIFFERENCE_THRESHOLD=10.0
      - HAPPY_TO_SAD_DIFFERENCE_THRESHOLD=10.0
      - NEUTRAL_TO_SURPRISED_THRESHOLD=10.0
      - FEAR_THRESHOLD=5.0
      - HAPPY_THRESHOLD=20.0
      - DISGUST_ANGRY_THRESHOLD=12.5
      - SAD_THRESHOLD=15.0
    ports:
      - "3030:3000"
  frontend:
    container_name: node-frontend
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
  prometheus:
    image: prom/prometheus
    depends_on:
      - python-backend
    ports:
      - 9090:9090
  grafana:
    image: grafana/grafana
    depends_on:
      - prometheus
    ports:
      - 3000:3000