version: "3.9"
services:
  python-backend:
    container_name: python-backend
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "4040:4040"
  frontend:
    container_name: node-frontend
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
  prometheus:
    image: prom/prometheus
    depends_on:
      - python-backend
    ports:
      - 9090:9090
  grafana:
    image: grafana/grafana
    depends_on:
      - prometheus
    ports:
      - 3000:3000